config:
  applicationAliasMap:
    - uuid: uuid1
      name: app1
    - uuid: uuid2
      name: app2
    - uuid: uuid3
      name: app3
  publicMessageTopics:
    - 'v2x/+/public/#'
  applicationTypes:
    - "denm"
    - "ivim"